### ISSUE TITLE
[Bug]: FO won't install (1.19.3)

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#63] opened 2023-01-03 18:37 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When selecting 1.19.3 beta from the installer and clicking install, the installer seems to get stuck on "Installing Fabric..." process.

### Version

Beta release

### What platform are you using?

Windows

### How did you download the software?

GitHub Releases

### Relevant log output

```bash
Where?
```

**Comment by osfanbuff63** [comment] 2023-01-05 00:45
For later, I can reproduce and it gives an `UnboundLocalError`...

**Comment by osfanbuff63** [comment] 2023-01-11 19:23
Having looked into this a bit more, I think it's an issue going back to installing Fabric - because the `UnboundLocalError` is with `version_id`, which is only used in that function. But how is that variable not being assigned?

**Comment by Madis0** [comment] 2023-02-08 18:58
Still present on beta 2

**Comment by osfanbuff63** [comment] 2023-02-09 12:54
Figured out the issue here - it's looking for a folder named "1.19.3 (beta)" because that's what's shown in the UI, but the backend doesn't resolve that to look for the folder in FO repo named "1.19.3" (or rather, Packwiz/1.19.3).

**Comment by Madis0** [comment] 2023-02-09 12:57
In that case the JSON could have separate visible name and folder name.

**Comment by osfanbuff63** [comment] 2023-02-09 13:04
I also figured out that when installing Fabric, we're manually resolving the version, instead of using the JSON (which was used in `get_pack_mc_versions` and `newest_version`) - so resolving from the JSON instead should fix this issue and prevent other similar ones.

**Closed as completed** 2023-02-09 13:16 UTC
Labels: bug, important
